# Generated by Django 4.0.6 on 2023-11-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimental_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500)),
                ('catergory', models.CharField(max_length=100, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
